services:
  - type: web
    name: football-games
    runtime: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.11.0
      - key: NODE_ENV
        value: production
